 version: 2.1
 orbs:
 #  newman: postman/newman@0.0.2
 jobs:
 #  postman:
  #   executor: newman/postman-newman-docker
   #  docker:
    #   - image: circleci/node:lts
    #   - image: circleci/mongo:latest
  #   environment:
   #    - MONGO_URL: "mongodb://localhost:27017/herodb"
  #   steps:
   #    - checkout
  #     - run: npm install
  #     - run: npm run express-server
 #      - newman/newman-run:
   #        collection: .circleci/postman_test.json
   #        timeout: '1000'
   jest:
     docker:
       - image: circleci/node:6.13.0
   #    - image: circleci/mongo:latest
     environment:
       - MONGO_URL: "mongodb://localhost:27017/herodb"
 #    working_directory: ~/
     steps:
       - run: npm update
       - checkout
       - restore_cache:
           keys:
             - cache1-{{ checksum "package.json" }}
       - run: ls -l ~/project
       - run: npm install -g
       - save_cache:
           paths:
             - ~/node_modules
           key: cache1-{{ checksum "package.json"}}
  #     - run: npm run seed-db
       - run: npm test
 workflows:
   version: 2.1
   postman_and_main:
     jobs:
  #    - postman
      - jest