 version: 2
 orbs:
   newman: postman/newman@1.0.0
 jobs:
   newman-collection-run:
     executor: newman/postman-newman-docker
     steps:
       - checkout
       - newman/newman-run:
           collection: ./.circleci/postman-express-test.postman_collection.json
   build:
     docker:
       - image: circleci/node:lts
     steps:
       - checkout
       - run: echo "A first hello"
       - run: npm install
       - run: npm test