 version: 2.1
 orbs:
   newman: postman/newman@0.0.2
 jobs:
   postman:
     executor: newman/postman-newman-docker
     docker:
       - image: circleci/node:lts
       - image: circleci/mongo:latest
     environment:
       - MONGO_URL: "mongodb://localhost:27017/herodb"
     steps:
       - checkout
   #    - run: npm install
     #  - run: npm run express-server
       - newman/newman-run:
           collection: .circleci/postman_test.json
           timeout: '1000'
   main-node:
     docker:
       - image: circleci/node:lts
       - image: circleci/mongo:latest
     environment:
       - MONGO_URL: "mongodb://localhost:27017/herodb"
     steps:
       - checkout
       - run: echo "A first hello"
       - run: npm test
 workflows:
   version: 2.1
   postman_and_main:
     jobs:
      - postman
      - main-node