 version: 2
 orbs:
   newman: postman/newman@4.4.1
 jobs:
   postman:
     executor: newman/postman-newman-docker
     steps:
       - checkout
       - newman/newman-run:
           collection: ./.circleci/postman-express-test.postman_collection.json
   main-node:
     docker:
       - image: circleci/node:lts
     steps:
       - checkout
       - run: echo "A first hello"
       - run: npm install
       - run: npm test